#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/assemble-pages.sh --in <dir> --out <dir>

Input directory is expected to contain one subdirectory per artifact:
  <in>/openwrt-repo-<board>/...

Output directory will contain:
  <out>/openwrt-<ver>/<board>/...
EOF
}

die() {
  echo "error: $*" >&2
  exit 1
}

IN_DIR=""
OUT_DIR=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --in) IN_DIR="${2:-}"; shift 2 ;;
    --out) OUT_DIR="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown arg: $1" ;;
  esac
done

[[ -n "$IN_DIR" ]] || { usage; die "--in is required"; }
[[ -n "$OUT_DIR" ]] || { usage; die "--out is required"; }

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

shopt -s nullglob
artifacts=("$IN_DIR"/openwrt-repo-*)
shopt -u nullglob
[[ ${#artifacts[@]} -gt 0 ]] || die "No artifacts found under '$IN_DIR'"

links=()

for d in "${artifacts[@]}"; do
  buildinfo="$d/BUILDINFO.txt"
  [[ -f "$buildinfo" ]] || die "Missing BUILDINFO.txt in artifact '$d'"

  ver=""
  board=""
  while IFS='=' read -r k v; do
    case "$k" in
      OPENWRT_VERSION) ver="$v" ;;
      BOARD) board="$v" ;;
    esac
  done < "$buildinfo"

  [[ -n "$ver" ]] || die "OPENWRT_VERSION missing in $buildinfo"
  [[ -n "$board" ]] || die "BOARD missing in $buildinfo"

  links+=("${ver}|${board}")

  dest="$OUT_DIR/openwrt-${ver}/${board}"
  mkdir -p "$dest"
  rsync -a "$d/" "$dest/"
done

# Generate a tiny index. Keep it dumb: just list what we built.
{
  echo '<!doctype html>'
  echo '<meta charset="utf-8">'
  echo '<title>OpenWrt fluent-bit packages</title>'
  echo '<h1>OpenWrt fluent-bit packages</h1>'
  echo '<p>This site is generated by GitHub Actions.</p>'
  echo '<ul>'

  seen=""
  for item in "${links[@]}"; do
    case " $seen " in *" $item "*) continue ;; esac
    seen+=" $item"

    ver="${item%%|*}"
    board="${item#*|}"
    printf '  <li><a href="openwrt-%s/%s/">openwrt-%s / %s</a></li>\n' "$ver" "$board" "$ver" "$board"
  done

  echo '</ul>'
} >"$OUT_DIR/index.html"
